"""Add updated_at to Model

Revision ID: bd97498a7d5b
Revises: 30051a700bea
Create Date: 2025-03-20 23:34:00.220741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd97498a7d5b'
down_revision: Union[str, None] = '30051a700bea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'updated_at')
    # ### end Alembic commands ###
