"""table update

Revision ID: e818c7ebab44
Revises: 9bcac6ecd5a8
Create Date: 2025-04-03 20:32:35.276366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e818c7ebab44'
down_revision: Union[str, None] = '9bcac6ecd5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
